namespace eval ::flutiou {
    ::msgcat::mcflmset {        \
        "File" "Fichier"        \
        "Appearance" "Apparence" \
        "Browse" "Parcourir"    \
        "Configure" "Configurer" \
        "Quit" "Quiter"         \
        "Filter" "Filtrer"      \
        "Save" "Sauvegarder"    \
        "Play" "Jouer"          \
        "Stop" "Stop"           \
        "Next" "Suivant"        \
        "Previous" "Précédant"  \
        "Undo" "Défaire"        \
        "Redo" "Refaire"        \
        "Clear" "Nettoyer"      \
        "Tracks" "Pistes"       \
        "Track" "Piste"         \
        "tracks" "Pistes"       \
        "Edit filters" "Editer les filtres" \
        "Configure column heading..."  "Configurer les entêtes de colone..." \
        "Playlist" "Liste de lecture" \
        "track" "Piste"         \
        "Playing: %1$s by %2$s %3$s" "Joue %1$s de %2$s %3$s" \
        "File name" "Nom de fichier" \
        "Search" "Chercher"     \
    }
}
